"""
Celery tasks for transcript generation.

Each step emits a step-log to Redis (job_store) and calls `checkpoint()` so the
job can be paused or stopped between steps. MongoDB side-effects are delegated
to `hooks`, keeping this module small and single-purpose.
"""
from __future__ import annotations
import os
import sys
import logging
import shutil
import traceback
from celery import Task

from app.core.celery_app import celery_app
from app.core.config import settings
from app.core.job_store import (
    set_job_done, set_job_failed, set_job_stopped, clear_control, set_transcript_id,
    set_transcription_retry, clear_transcription_retry,
    STEP_RESOLVING, STEP_FOUND, STEP_DOWNLOADING,
    STEP_EXTRACTING, STEP_UPLOADING, STEP_TRANSCRIBING, STEP_SAVING, STEP_FAILED,
)
from app.tasks.control import checkpoint, make_logger, StopRequested
from app.tasks import hooks, fastpath
from app.services.resolver.media_resolver import resolve_candidates
from app.services.resolver.url_classifier import is_direct_media_url, is_youtube_url
from app.services.downloader.audio_pipeline import acquire_audio, cleanup
from app.services.downloader.ffmpeg_extractor import extract_audio_from_upload
from app.services.downloader.binary_finder import find_ffmpeg
from app.services.transcriber.caption_generator import (
    generate_captions, generate_captions_from_url,
)
from app.services.transcriber.chunked_transcriber import generate_chunked_aligned_srt
from app.services.transcriber.whisper_transcriber import transcribe_to_srt
from app.services.transcriber.mime_types import ext_to_mime

logger = logging.getLogger(__name__)


@celery_app.task(bind=True, name="transcript.from_url", max_retries=0)
def transcribe_url_task(
    self: Task,
    job_id: str,
    url: str,
    meeting_id: str = "",
    actor: str = "system",
) -> dict:
    """Process a video URL end-to-end: resolve → download → transcribe → save."""
    log = make_logger(job_id, logger)
    audio_path: str | None = None
    preserve_audio = False
    try:
        transcript_id = _begin(job_id, meeting_id)

        checkpoint(job_id)
        log(STEP_RESOLVING, f"Searching for video at: {url}")
        candidates = resolve_candidates(url)
        log(STEP_FOUND, f"Found {len(candidates)} media candidate(s): {candidates[0]}")

        # Fast-path: reuse existing captions/subtitles instead of audio + Gemini.
        # YouTube exposes a transcript API; other players (e.g. Granicus) sometimes
        # ship an embedded VTT we can pull without downloading the media.
        checkpoint(job_id)
        # Gemini mode keeps the free caption fast paths. Local Whisper modes
        # intentionally process the audio so every result has the same timed SRT
        # format and is generated by the selected engine.
        if settings.TRANSCRIPTION_ENGINE == "gemini":
            if is_youtube_url(url):
                done = fastpath.try_captions(job_id, log, url, meeting_id, transcript_id, actor)
            else:
                done = fastpath.try_subtitles(job_id, log, url, meeting_id, transcript_id, actor)
            if done is not None:
                return done

        checkpoint(job_id)
        log(STEP_DOWNLOADING, "Downloading / extracting audio...")
        try:
            audio_path = acquire_audio(
                candidates=candidates,
                original_url=url,
                log=lambda msg: log(STEP_DOWNLOADING, msg),
            )
        except Exception as exc:
            remote_result = _try_remote_media_transcription(
                job_id, log, candidates, url, meeting_id, transcript_id, actor, exc
            )
            if remote_result is not None:
                return remote_result
            raise
        size_mb = os.path.getsize(audio_path) / 1024 / 1024
        log(STEP_EXTRACTING, f"Audio ready: {os.path.basename(audio_path)} ({size_mb:.1f} MB)")

        checkpoint(job_id)
        transcript = _transcribe(job_id, log, audio_path)

        # Keep the downloaded audio so the transcription step can be rerun without
        # re-downloading the (often large) media. Preserve BEFORE set_job_done so
        # the final status stays DONE.
        if settings.KEEP_AUDIO_FOR_RERUN and audio_path and os.path.exists(audio_path):
            cached_path = _preserve_for_retry(job_id, audio_path, logger)
            if cached_path:
                audio_path = cached_path
                preserve_audio = True
                set_transcription_retry(job_id, audio_path, "keep")

        log(STEP_SAVING, f"Saving transcript ({len(transcript)} chars)...")
        hooks.on_success(meeting_id, transcript_id, transcript, actor, source_label=url)
        set_job_done(job_id, transcript)
        return {"status": "done", "transcript": transcript}

    except StopRequested:
        set_job_stopped(job_id)
        hooks.on_stopped(meeting_id, actor)
        return {"status": "stopped"}
    except Exception as exc:
        # Whatever went wrong after the audio was in hand (transcription, saving,
        # a transient Gemini outage…), keep the audio so the user can retry only
        # the failed steps instead of re-downloading the whole media.
        if audio_path and os.path.exists(audio_path):
            cached_path = _preserve_for_retry(job_id, audio_path, logger)
            if cached_path:
                audio_path = cached_path
                preserve_audio = True
                set_transcription_retry(job_id, audio_path, "file")
                log(STEP_FAILED, "Audio was preserved — use “Retry failed steps” to resume without downloading again.", level="warn")
        _fail(job_id, str(exc), meeting_id, actor, log)
        raise
    finally:
        clear_control(job_id)
        if audio_path and not preserve_audio:
            cleanup(audio_path)


@celery_app.task(bind=True, name="transcript.from_upload", max_retries=0)
def transcribe_upload_task(
    self: Task,
    job_id: str,
    file_path: str,
    original_filename: str,
    is_video: bool = False,
    meeting_id: str = "",
    actor: str = "system",
) -> dict:
    """Process an uploaded audio or video file."""
    log = make_logger(job_id, logger)
    audio_path: str | None = None
    preserve_audio = False
    try:
        transcript_id = _begin(job_id, meeting_id)

        checkpoint(job_id)
        log(STEP_FOUND, f"Received file: {original_filename}")
        audio_path = _prepare_upload(job_id, log, file_path, original_filename, is_video)

        checkpoint(job_id)
        transcript = _transcribe(job_id, log, audio_path)

        if settings.KEEP_AUDIO_FOR_RERUN and audio_path and os.path.exists(audio_path):
            cached_path = _preserve_for_retry(job_id, audio_path, logger)
            if cached_path:
                audio_path = cached_path
                preserve_audio = True
                set_transcription_retry(job_id, audio_path, "keep")

        log(STEP_SAVING, f"Saving transcript ({len(transcript)} chars)...")
        hooks.on_success(meeting_id, transcript_id, transcript, actor, source_label=original_filename)
        set_job_done(job_id, transcript)
        return {"status": "done", "transcript": transcript}

    except StopRequested:
        set_job_stopped(job_id)
        hooks.on_stopped(meeting_id, actor)
        return {"status": "stopped"}
    except Exception as exc:
        # Keep the prepared audio on any post-preparation failure so the user can
        # retry only the failed steps without re-uploading.
        if audio_path and os.path.exists(audio_path):
            cached_path = _preserve_for_retry(job_id, audio_path, logger)
            if cached_path:
                audio_path = cached_path
                preserve_audio = True
                set_transcription_retry(job_id, audio_path, "file")
                log(STEP_FAILED, "Audio was preserved — use “Retry failed steps” to resume without re-uploading.", level="warn")
        _fail(job_id, str(exc), meeting_id, actor, log)
        raise
    finally:
        clear_control(job_id)
        _cleanup_upload(file_path, audio_path, is_video, preserve_audio)


@celery_app.task(bind=True, name="transcript.retry_cached_audio", max_retries=0)
def retry_cached_audio_task(
    self: Task, job_id: str, audio_path: str, cleanup_mode: str,
    meeting_id: str = "", actor: str = "system", source_label: str = "",
    engine_override: str = "",
) -> dict:
    """Retry only Gemini transcription using audio retained by a failed job."""
    log = make_logger(job_id, logger)
    preserve_audio = False
    try:
        if not os.path.isfile(audio_path):
            raise RuntimeError("Preserved audio is no longer available; rerun the full job.")
        transcript_id = _begin(job_id, meeting_id)
        clear_transcription_retry(job_id)
        log(STEP_FOUND, f"Reusing preserved audio: {os.path.basename(audio_path)}")
        checkpoint(job_id)
        transcript = _transcribe(job_id, log, audio_path, engine_override=engine_override)
        log(STEP_SAVING, f"Saving transcript ({len(transcript)} chars)...")
        hooks.on_success(meeting_id, transcript_id, transcript, actor, source_label=source_label)
        set_job_done(job_id, transcript)
        return {"status": "done", "transcript": transcript, "source": "cached_audio"}
    except StopRequested:
        set_job_stopped(job_id)
        hooks.on_stopped(meeting_id, actor)
        return {"status": "stopped"}
    except Exception as exc:
        # Retry failed again — keep the audio so it can be retried once more.
        if os.path.isfile(audio_path):
            preserve_audio = True
            set_transcription_retry(job_id, audio_path, cleanup_mode)
            log(STEP_FAILED, "The step failed again — the audio remains available for another retry.", level="warn")
        _fail(job_id, str(exc), meeting_id, actor, log)
        raise
    finally:
        clear_control(job_id)
        if not preserve_audio:
            _cleanup_cached_audio(audio_path, cleanup_mode)


# ── Shared helpers ────────────────────────────────────────────────────────────

def _begin(job_id: str, meeting_id: str) -> str:
    """Resolve the meeting's transcript (find-or-create), mark it generating, and
    record the id on the job for display. Returns "" when no meeting is linked."""
    transcript_id = hooks.on_generating(meeting_id)
    if transcript_id:
        set_transcript_id(job_id, transcript_id)
    return transcript_id


def _prepare_upload(job_id, log, file_path, original_filename, is_video) -> str:
    """Return the audio path to transcribe, extracting from video when needed."""
    if not is_video:
        log(STEP_EXTRACTING, "Audio file — no extraction needed")
        return file_path
    ffmpeg = find_ffmpeg()
    if not ffmpeg:
        raise RuntimeError("ffmpeg is required to extract audio from video but was not found.")
    log(STEP_EXTRACTING, f"Extracting audio from video: {original_filename}")
    audio_path = extract_audio_from_upload(ffmpeg, file_path)
    log(STEP_EXTRACTING, f"Audio extracted: {os.path.basename(audio_path)}")
    return audio_path


def _transcribe(job_id, log, audio_path: str, engine_override: str = "") -> str:
    size_mb = os.path.getsize(audio_path) / 1024 / 1024
    step = lambda msg: log(STEP_TRANSCRIBING, msg)
    engine = engine_override or settings.TRANSCRIPTION_ENGINE
    if engine not in {"gemini", "whisper", "whisper_gemini_fallback"}:
        raise RuntimeError(f"Unsupported TRANSCRIPTION_ENGINE: {engine}")

    if engine in {"whisper", "whisper_gemini_fallback"}:
        log(STEP_TRANSCRIBING, f"Transcribing {size_mb:.1f} MB locally with faster-whisper...")
        try:
            return transcribe_to_srt(audio_path, log=step)
        except Exception as exc:
            if engine == "whisper":
                raise
            logger.exception("Local Whisper failed; falling back to Gemini: %s", exc)
            log(STEP_TRANSCRIBING,
                "Local Whisper failed — falling back to Gemini.", level="warn")

    return _transcribe_gemini(log, audio_path, size_mb, step)


def _transcribe_gemini(log, audio_path: str, size_mb: float, step) -> str:
    # Chunked pipeline: split the audio (Gemini can't transcribe multi-hour audio
    # in one request), transcribe + force-align each chunk, stitch into one SRT.
    # If the whole pipeline fails, fall back to a single-shot Gemini SRT.
    log(STEP_TRANSCRIBING, f"Transcribing {size_mb:.1f} MB in chunks (Gemini + alignment)...")
    try:
        return generate_chunked_aligned_srt(audio_path, log=step)
    except Exception as exc:
        logger.warning("Chunked transcription failed (%s); using single-shot Gemini", exc)
        log(STEP_TRANSCRIBING,
            "Chunked path failed — falling back to a single Gemini pass.", level="warn")
        return generate_captions(audio_path, fmt="srt", log=step)


def _try_remote_media_transcription(
    job_id,
    log,
    candidates: list[str],
    original_url: str,
    meeting_id: str,
    transcript_id: str,
    actor: str,
    download_error: Exception,
) -> dict | None:
    if settings.TRANSCRIPTION_ENGINE == "whisper":
        # Local Whisper requires a local file. Preserve the original acquisition
        # error instead of silently sending media to an external provider.
        return None
    media_url = next((c for c in candidates if is_direct_media_url(c)), None)
    if not media_url:
        return None

    _, ext = os.path.splitext(media_url)
    mime = ext_to_mime(ext)
    log(
        STEP_TRANSCRIBING,
        "Server download failed; asking Gemini to fetch the media URL directly.",
        level="warn",
    )
    logger.warning("Falling back to Gemini URL transcription after download failure: %s", download_error)
    transcript = generate_captions_from_url(
        media_url,
        mime,
        fmt="srt",
        log=lambda msg: log(STEP_TRANSCRIBING, msg),
    )
    log(STEP_SAVING, f"Saving transcript ({len(transcript)} chars)...")
    hooks.on_success(meeting_id, transcript_id, transcript, actor, source_label=original_url)
    set_job_done(job_id, transcript)
    return {"status": "done", "transcript": transcript, "source": "gemini_url"}


def _fail(job_id, error_msg, meeting_id, actor, log) -> None:
    # A bare message like KeyError's "'file'" is useless on its own. When we are
    # inside an active exception, capture the type and last traceback frame so the
    # job log points at the real failing line; the full trace goes to the worker log.
    exc_type, exc, tb = sys.exc_info()
    if exc is not None:
        logger.exception("Job %s failed: %s", job_id, error_msg)
        frame = traceback.extract_tb(tb)[-1] if tb else None
        detail = f"{exc_type.__name__}: {error_msg}"
        if frame:
            detail += f"  (at {os.path.basename(frame.filename)}:{frame.lineno} in {frame.name})"
        log(STEP_FAILED, detail, level="error")
    else:
        log(STEP_FAILED, error_msg, level="error")
    set_job_failed(job_id, error_msg)
    hooks.on_failure(meeting_id, error_msg, actor)


def _preserve_for_retry(job_id: str, audio_path: str, log: logging.Logger) -> str | None:
    """Move audio from worker-local /tmp into the web/worker shared uploads volume."""
    try:
        retry_dir = os.path.join(settings.UPLOAD_DIR, "retry-cache")
        os.makedirs(retry_dir, exist_ok=True)
        ext = os.path.splitext(audio_path)[1] or ".audio"
        destination = os.path.join(retry_dir, f"{job_id}{ext}")
        original_parent = os.path.dirname(audio_path)
        shutil.move(audio_path, destination)
        if original_parent and original_parent != settings.UPLOAD_DIR:
            try:
                os.rmdir(original_parent)
            except OSError:
                pass
        return destination
    except Exception:
        log.exception("Could not preserve audio for a transcription retry")
        return None


def _cleanup_cached_audio(audio_path: str, cleanup_mode: str) -> None:
    if cleanup_mode == "keep":
        return  # persistent rerun cache — only removed when the job is deleted
    if cleanup_mode == "temp":
        cleanup(audio_path)
        return
    try:
        if audio_path and os.path.exists(audio_path):
            os.remove(audio_path)
    except Exception:
        pass


def _cleanup_upload(file_path, audio_path, is_video, preserve_audio=False) -> None:
    try:
        if file_path and os.path.exists(file_path) and not (preserve_audio and audio_path == file_path):
            os.remove(file_path)
    except Exception:
        pass
    if is_video and audio_path and audio_path != file_path and not preserve_audio:
        cleanup(audio_path)
